### ISSUE TITLE
Adding a screenshot feature

### ISSUE THREAD

**Issue by maaaaz** [yahoo/gryffin#11]
Hello,

Following the very same approach as [Netflix Scumblr](https://github.com/Netflix/Scumblr), it would be great if you could add a **screenshot feature for each scanned site** (each page ?).
I don't mean to advertise but I got a functional [phantomjs script ready](https://github.com/maaaaz/webscreenshot) for that purpose.

Cheers.

**Comment by r-andrew-dev** [comment]
Project is being archived.
