### ISSUE TITLE
Fuzzer integration and XSS testing

### ISSUE THREAD

**Issue by mutantzombie** [yahoo/gryffin#14]
The fuzzing integration seems to be limited to launching against a single URL in a per-process model, as noted in #9.

How does this support testing for stored XSS that requires injection into one page, but checking for the payload's display in another page? Is a relevant fuzzer expected to perform its own crawl and output analysis to discover the display page? If so, how does a test against a subsequent URL re-use that fuzzer's state if only STDOUT is captured?

**Comment by r-andrew-dev** [comment]
The project is being archived.
