### ISSUE TITLE
Decoupling of crawl and audit (fuzzers)

### ISSUE THREAD

**Issue by mutantzombie** [yahoo/gryffin#16]
The broad decoupling of the crawl and audit seems to limit how well this could grow in terms of accuracy and optimizations.

Each fuzzer apparently only receives state (cookies) and a URL. It doesn't benefit from content or patterns learned during the crawl, such as custom error pages. For example, this limits optimizations that would be useful for testing for persistent and stored XSS as noted in #14. It would also be useful for reducing false positives when looking for common paths or page names.

It's not clear how a fuzzer that discovers new links that the crawler missed, such as via content inspection or guessing path or page names, could feed those links back to be crawled and further audited unless the fuzzer explicitly does so.

A fuzzer that goes through steps to profile a page for default content or custom errors wouldn't be able to share that info with another fuzzer. (This is a limitation both of the architecture and the fuzzers -- they'd need to share a data model.)

The performance characteristics (concurrent requests, requests/sec.) of the crawl may differ significantly from the fuzzers unless each one is pre-configured with identical thresholds. This would cause high variance in the impact on the target.

**Comment by r-andrew-dev** [comment]
The project is being archived.
