### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ghost** [yahoo/gryffin#20]
Whenever I try to install gryffin, I get this error:
# github.com/yahoo/gryffin

src/github.com/yahoo/gryffin/gryffin.go:226:24: error: reference to undefined field or method ‘Timeout’
   client.(*http.Client).Timeout = time.Duration(3) \* time.Second

Please assist,
Thank you.

**Comment by yukinying** [comment]
Could we know what version of go you are using? i.e. what you got when you run `go version`?

**Comment by ghost** [comment]
Hey @yukinying 
Sure,

go version xgcc (Ubuntu4.9.1-0ubuntu1) 4.9.1 linux/amd64

**Comment by yukinying** [comment]
xgcc implies the use of gccgo, and gccgo 4.9 use go 1.2 which is a relatively old version of Go. Some standard libraries has changed dramatically from 1.2 to 1.4, thus you got those errors. The best way to resolve this is to use Go 1.5 from https://golang.org/doc/install.

**Comment by ghost** [comment]
Fantastic, Please add to the doc that it required Go 1.5 because I just went with the easier way through apt-get.

Thank you, installation was successful and currently crawling successfully.
