### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by bararchy** [yahoo/gryffin#23]
So, at last I managed to make gryffin-standalone do a full (successful ?) scan.
After the run is finished I get this:

```
gryffin-standalone http://192.168.1.117:1912/login
=== Running Gryffin ===
{"Service":"Main","Msg":"Started","Method":"GET","Url":"http://192.168.1.117:1912/login"}
{"Service":"Poke","Msg":"Poking","Method":"GET","Url":"http://192.168.1.117:1912/login"}
{"Service":"CrawlAsync","Msg":"Started","Method":"GET","Url":"http://192.168.1.117:1912/login"}
{"Service":"PhantomjsRenderer.Do","Msg":"Running: render.js","Method":"GET","Url":"http://192.168.1.117:1912/login"}
{"Service":"Fingerprint","Msg":"Computed","Method":"GET","Url":"http://192.168.1.117:1912/login"}
{"Service":"IsDuplicatedPage","Msg":"Unique Page","Method":"GET","Url":"http://192.168.1.117:1912/login"}
{"Service":"ShouldCrawl","Msg":"Unique Link","Method":"POST","Url":"http://192.168.1.117:1912/afterLogin"}
{"Service":"Arachni.Scan","Msg":"Run as [arachni --checks xss* --output-only-positives --http-request-concurrency 1 --http-request-timeout 10000 --timeout 00:03:00 --scope-dom-depth-limit 0 --scope-directory-depth-limit 0 --scope-page-limit 1 --audit-with-both-methods --report-save-path /dev/null --snapshot-save-path /dev/null http://192.168.1.117:1912/login]","Method":"GET","Url":"http://192.168.1.117:1912/login"}
{"Service":"SQLMap.Scan","Msg":"Run as [sqlmap --batch --timeout=2 --retries=3 --crawl=0 --disable-coloring -o --text-only -v 0 --level=1 --risk=1 --smart --fresh-queries --purge-output --os=Linux --dbms=MySQL --delay=0.1 --time-sec=1 -u http://192.168.1.117:1912/login]","Method":"GET","Url":"http://192.168.1.117:1912/login"}
{"Service":"CrawlAsync","Msg":"Started","Method":"POST","Url":"http://192.168.1.117:1912/afterLogin"}
{"Service":"PhantomjsRenderer.Do","Msg":"Running: render.js","Method":"POST","Url":"http://192.168.1.117:1912/afterLogin"}
{"Service":"IsDuplicatedPage","Msg":"Duplicate Page","Method":"POST","Url":"http://192.168.1.117:1912/afterLogin"}
{"Service":"PhantomjsRenderer.Do","Msg":"[Cleanup] Terminating the crawl process.","Method":"POST","Url":"http://192.168.1.117:1912/afterLogin"}
{"Service":"Get Links","Msg":"Finished","Method":"POST","Url":"http://192.168.1.117:1912/afterLogin"}
{"Service":"SQLMap.Scan","Msg":"SQLMap return true","Method":"GET","Url":"http://192.168.1.117:1912/login"}
{"Service":"Arachni.Scan","Msg":"Arachni return true","Method":"GET","Url":"http://192.168.1.117:1912/login"}
{"Service":"ShouldCrawl","Msg":"Duplicate Link","Method":"GET","Url":"http://192.168.1.117:1912/afterLogin"}
{"Service":"Get Links","Msg":"Finished","Method":"POST","Url":"http://192.168.1.117:1912/afterLogin"}
=== End Running Gryffin ===
```

Did the output saves at another place ? is this all of the results ? what info can I get from this ? 
Also, it was really too fast to be a full sqlmap run on the login form

P.S 
If gryffin detects a form, it should maybe try to run sqlmap with the `--forms` flag

**Comment by yukinying** [comment]
> Did the output saves at another place ? is this all of the results ? what info can I get from this ? 

The idea is that if you are running web scanning as an infrastructure, we suggest having the result processed using existing solutions that could do the visualization well. There are quite some commercial products that could process log data very well. If you are looking at open source products, one of which is Kibana (come with Elastic search). Gryffin currently would probe the port 5000 of the localhost. 

Gryffin is a simple and straightforward implementation (same as many other Go project) that one could dig into the actual implementation quickly. The processing of sqlmap result is done here: https://github.com/yahoo/gryffin/blob/master/fuzzer/sqlmap/sqlmap.go . And there is no magic there, the code for identifying findings is:

```
            g.Logm("SQLMap.Findings", l)
```

Yet, I would probably add a different Log level so one can quickly filter the results. 

> Also, it was really too fast to be a full sqlmap run on the login form

The sqlmap command is run with "--delay=0.1" "--time-sec=1" currently. We have a plan to make the rate limiting module be taking the feedback from the fuzzers, but it would probably take more time to get the idea be done in the proper way.

> If gryffin detects a form, it should maybe try to run sqlmap with the --forms flag

Thanks for pointing that out. Let me add it back.

**Comment by bararchy** [comment]
I see, I downloaded and configured the docker image and played around with Kibana.
When I see `Service:   Arachni.Scan   Msg:   Arachni return true`
Is the "true" symbolized a finding or just answer received ?

**Comment by yukinying** [comment]
Currently we track the process exit code and return true if the command is executed successfully. The whole fuzzer plugin (with commandline tools) are extremely easy to write and please feel free to give us pull requests for potential improvement! 
Here are the sample plugins:
- https://github.com/yahoo/gryffin/blob/master/fuzzer/arachni/arachni.go 
- https://github.com/yahoo/gryffin/blob/master/fuzzer/sqlmap/sqlmap.go

**Comment by r-andrew-dev** [comment]
The project is being archived.
