### ISSUE TITLE
Login the application through Gryffin.

### ISSUE THREAD

**Issue by VishnuSanap** [yahoo/gryffin#31]
@yukinying I have run gryffin successfully but wanted to know how should I pass uername and password to Gryffin for login and create session. For scanning of whole application it is needed to login the application through Gryffin.
For EX: We do it in SQLMap like,
./sqlmap.py --url="http://www.example.com/Login" --data="UserName=xyz&Password=xyz@123" --banner
Please suggest answer ASAP.

**Comment by r-andrew-dev** [comment]
The project is being archived.
