### ISSUE TITLE
README.md - Image is missing

### ISSUE THREAD

**Issue by NedkoHristov** [yahoo/gryffin#32]
On the project page - one of the images ( https://camo2.githubusercontent.com/5b1cc806dab335a9f72fa6421a5ddf2189aa26fa/68747470733a2f2f7472617669732d63692e6f72672f7961686f6f2f6772796666696e2e7376673f6272616e63683d6d6173746572 ) is not loaded correctly due of missing image.

![3](https://cloud.githubusercontent.com/assets/5328274/16113116/70254fbe-33c3-11e6-868b-bdcf86334a1e.png)

**Comment by r-andrew-dev** [comment]
The project is being archived.
