### ISSUE TITLE
gryffin/html-distance/cmd/html-distance

### ISSUE THREAD

**Issue by suntong** [yahoo/gryffin#34]
In https://github.com/yahoo/gryffin/tree/master/html-distance, it says, 

to install, do 

`go install github.com/yahoo/gryffin/html-distance/cmd/html-distance
`

but I don't see the gryffin/html-distance/cmd/html-distance within this repo. 
Please double-check. Thx.

**Comment by r-andrew-dev** [comment]
The project is being archived.
