### ISSUE TITLE
Page deduplication drawbacks?

### ISSUE THREAD

**Issue by Zapotek** [yahoo/gryffin#6]
Hey guys,

The [page deduplication](https://github.com/yahoo/gryffin#page-deduplication) approach is clever, but it sets a hard limit on the scanner's issue detection capabilities.

Since you're comparing HTML code to determine uniqueness, it guarantees that certain issues exposed via text nodes will not be able to be identified, as those pages will never make it to the underlying scanner.
For example, disclosure of sensitive information such as credit card numbers, SSN, etc.

In addition, it also prevents you from identifying server-side resources, like sensitive files and directories (backup, backdoors, etc.); the URL of a template-generated page whose path can be manipulated into returning a sensitive file will never make it to the scanner.

I can see that right now you're only interested in SQL and XSS issues, but the architecture seems limited to only identifying active issues.

Was that a conscious decision?

Cheers,
Tasos L.

**Comment by b1shan** [comment]
You are right @Zapotek. It is by design. 

Gryffin consciously tries not to overwhelm target website. This translates to less pages crawled due to deduplication. Hence, Gryffin is not suitable for content scanning.

**Comment by Zapotek** [comment]
The crawl occurs anyways since the deduplication happens based on HTML or some other criteria that first require the page to be retrieved, you're just skipping the audit (i.e. passing the page to the fuzzers).

Right?

**Comment by b1shan** [comment]
Yes @Zapotek. We do not crawl further from the duplicate page and the page/url itself is not sent to the fuzzer queue.

**Comment by Zapotek** [comment]
The problem with this approach is that for a page to be marked as a duplicate (and thus allow for the benefits of preventing further processing), it either needs to be a leaf on the site's tree, since it will have no discernible new paths, so you've already reached the end of the line, a full crawl has been performed. Or, due to the HTML distance algorithm, the overall size of the HTML nodes is big enough to mask the difference of a new (for example) `<a>` node that could point to a new path or even include new input vectors in its query.

The situation becomes worse still when considering that pages that may look like duplicates on the client-side, could in fact expose vulnerabilities on the server-side, usually via cookies or headers, which can be processed without warning or visible indication.

That would mean that a lot of effort is being spent in a deduplication process that doesn't have any upsides and will result in great loss of coverage even for cases which are within the intended scope.

And there's also the issue of being unable to pass DOM state to the fuzzers, just a URL and cookies.
Even if the crawler does its job, a massive amount of coverage gets lost when communicating the resources to the fuzzers.
For example, any issues that depend on JS code will currently go completely unnoticed, for example: pages creating forms/links via JS, JS loading HTML via AJAX, DOM-based XSS, DOM-based unvalidated redirects etc.

I don't mean to rag on Gryffin, I figured since it's still in beta this would be the right time to try and spot design issues.

**Comment by yukinying** [comment]
> And there's also the issue of being unable to pass DOM state to the fuzzers, just a URL and cookies.

I can't agree more on this. There seems to be a need to define a unified API between fuzzers in the industry so as to make information gathered at an upstream process to be usable in downstream fuzzers.

**Comment by yukinying** [comment]
> ... to mask the difference of a new (for example) <a> node that could point to a new path or even include new input vectors in its query

This may or may not be true for html-distance, that additional node would generate additional features that translates to more 1 or 0 bits and could change the fingerprint significantly. In our early version, we also try to add the url domain of anchor tag as an input feature for html-distance. We dropped it for simplicity, but we can always add it back. I'd wait until we see inputs from open community on how html-distance should be tuned, and then get it released in next minor version.

**Comment by yukinying** [comment]
> The situation becomes worse still when considering that pages that may look like duplicates on the client-side, could in fact expose vulnerabilities on the server-side, usually via cookies or headers, which can be processed without warning or visible indication.

Cookies, user-agent, and post body data should be part of the keys to distinguish the origin of the html. We currently just use "domain" for such purpose. We should definitely consider that something to be added in short term.

**Comment by yukinying** [comment]
> I don't mean to rag on Gryffin, I figured since it's still in beta this would be the right time to try and spot design issues.

Not at all. Actually we see this as an opportunities to collaborate with fuzzer authors. There is no easy way unless we discuss using the source code :)

**Comment by Zapotek** [comment]
> I can't agree more on this. There seems to be a need to define a unified API between fuzzers in the industry so as to make information gathered at an upstream process to be usable in downstream fuzzers.

I'm calling that DOM transitions in Arachni, they're attached to pages associated to relevant issues, you can get them from the reports.
They allow DOM state to be restored via a series of event triggers from `[element, event, options]` tuples.

> Cookies, user-agent, and post body data should be part of the keys to distinguish the origin of the html. We currently just use "domain" for such purpose. We should definitely consider that something to be added in short term.

Problem is that a cookie set by a page should be assumed to be an input for every other page as well.
That basically means that if you want cookies to be audited you can't deduplicate pages because any one of them can be vulnerable on the server-side.
Same thing goes for common (or custom) request headers as well, although I don't think you're currently auditing headers.

**Comment by yukinying** [comment]
> Problem is that a cookie set by a page should be assumed to be an input for every other page as well.
> That basically means that if you want cookies to be audited you can't deduplicate pages because any one of them can be vulnerable on the server-side.
> Same thing goes for common (or custom) request headers as well, although I don't think you're currently auditing headers.

Thanks for the input. I think I understand what you mean and I will push an update to get the dependencies between cookie / domain / user-agent against similarity detection fixed in next push.

**Comment by r-andrew-dev** [comment]
This project is being archived.
