### ISSUE TITLE
Cannot establish tcp connection to log listener

### ISSUE THREAD

**Issue by bararchy** [yahoo/gryffin#8]
I'm pretty new to go, so maybe I missed something, I keep getting this error:

```
make test-mono 
go run cmd/gryffin-standalone/main.go "http://127.0.0.1:8081"
Cannot establish tcp connection to log listener.
{"Service":"Main","Msg":"Started","Method":"GET","Url":"http://127.0.0.1:8081"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x47b4e4]

goroutine 1 [running]:
io.(*multiWriter).Write(0xc82000af40, 0xc82008eb40, 0x50, 0x95, 0x50, 0x0, 0x0)
    /usr/lib/go/src/io/multi.go:43 +0xd4
encoding/json.(*Encoder).Encode(0xc820051d48, 0x6b8240, 0xc820014680, 0x0, 0x0)
    /usr/lib/go/src/encoding/json/stream.go:201 +0x16b
github.com/yahoo/gryffin.(*Scan).Log(0xc8200e0bb0, 0x6b8240, 0xc820014680)
    /home/unshadow/go/src/github.com/yahoo/gryffin/gryffin.go:508 +0x96
github.com/yahoo/gryffin.(*Scan).Logm(0xc8200e0bb0, 0x7ca7e0, 0x4, 0x7cb3b8, 0x7)
    /home/unshadow/go/src/github.com/yahoo/gryffin/gryffin.go:495 +0x121
main.main()
    /home/unshadow/Desktop/git-projects/gryffin/cmd/gryffin-standalone/main.go:173 +0x4e4

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/lib/go/src/runtime/asm_amd64.s:1745 +0x1
exit status 2
Makefile:31: recipe for target 'test-mono' failed
make: *** [test-mono] Error 1

```

**Comment by yukinying** [comment]
Hi @bararchy ,

Thanks for the quick report. `go run cmd/gryffin-standalone/main.go` was an initial setup for quick integration test, and it depends on the ELK (elastic search, logstash, kibana) standing with a open port to parse the response.

The distributed version, `go run cmd/gryffin-distributed/main.go` is the recommended version, and it runs even without ELK. Yet this means you would totally rely on stdout to see the result.

We will prepare a better readme and setup instruction, which follows from the slides we used in appsec usa conference. Please stay tuned.

Albert

**Comment by bararchy** [comment]
Hi @yukinying Thanks for the feedback.

I managed to make it work thanks to your advice, Issue closed.

**Comment by yukinying** [comment]
We now ignore the error when tcp connection for log listener cannot be established. (https://github.com/yahoo/gryffin/pull/17)
