### ISSUE TITLE
Fuzzer integration issues

### ISSUE THREAD

**Issue by Zapotek** [yahoo/gryffin#9]
Hey guys,

I've noticed a few issues with the way that the fuzzers are currently integrated:
1. Spawning and monitoring is taking place via an STDOUT channel, which really isn't meant to be a programming interface but a user one[1]. UI output can change at any time and it really shouldn't be something to depend on for communicating data.
   1. Keeping the entire output buffer in memory instead of processing it as it arrives and then releasing it can be a problem too, depending on the amount of output.
   2. Output seems to be the **sole** source of data, instead for example also parsing a generated report at the end, this severely limits the amount of information that can be reported to the user.
2. Fuzzers are being cold-started for every resource, this will introduce a significant latency.

I can't speak for the rest but [Arachni](http://www.arachni-scanner.com/) is built to be a [distributed/integrable](http://www.arachni-scanner.com/features/framework/distributed-architecture/) system, so you can solve all of these issues by requesting warmed up scanner processes from a [Dispatcher](https://github.com/Arachni/arachni/wiki/RPC-server) (maintains a pool of initialized scanners, no spawn latency) and all integration (scanner dispatch, scan management and monitoring) happens via an [RPC API](https://github.com/Arachni/arachni/wiki/RPC-API).

[1] UNIX philosophy excluded.

**Comment by yukinying** [comment]
Hi @Zapotek 

I completely agree with you on the points stated. There are definitely lots of room for improvement :)

Let me explain how I see those:

> Spawning and monitoring is taking place via an STDOUT channel, which really isn't meant to be a programming interface but a user one[1]. UI output can change at any time and it really shouldn't be something to depend on for communicating data.
- PhantomJS: There are not many viable options for managing the data inflow and outflow from a PhantomJS process, as discussed in http://phantomjs.org/inter-process-communication.html. Ghostdriver (https://github.com/detro/phantomjs-ghostdriver) could be another option. However, our usage of PhantomJS v2 limited our choices. PhantomJS v2, with Webkit2 embedded, is more modern, and run faster. The downside is that v2 support of ghostdriver is pretty limited currently. Thus we made a compromise and use STDOUT. We have also considered websocket, or file IO, but I think they may create session management problem when running multiple PhantomJS in same box. In other words, it seems UNIX piping wins! 
- Memory of the output is less a concern, as compared to the memory footprint of PhantomJS in general.
- The pluggable architecture also supports the switch of different renderer. Once Ghostdriver support on PhantomJS v2 be more mature, we would definitely want to look at the possibility for moving to that.

> Fuzzers are being cold-started for every resource, this will introduce a significant latency
- Agree. The design for using CLI is for demonstrating how easy or hard it would be to add a new fuzzer plugin. We generally expect the users of Gryffin may build their own plugins following from the fuzzer samples, to deal with different use cases they may have. 
- And, indeed, in the version 1 of Gryffin, we use webservice based fuzzer. Moving the fuzzers to using webservice or rpc should be an interesting exercise.

Thanks a lot of the insight. And last but not least, pull requests are welcome!

**Comment by r-andrew-dev** [comment]
The project is being archived.
